name:                SpaceShooter
version:             0.1.0.0
github:              githubuser/SpaceShooter
license:             BSD3
author:              Aleksandra Kovacevic, Mirko Brkusanin
maintainer:          example@example.com
copyright:           2017 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Space Shooter game in Haskell using Gloss
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/test#readme>

dependencies:
- base >= 4.7 && < 5
- gloss

library:
  source-dirs: src

executables:
  SpaceShooter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SpaceShooter

tests:
  SpaceShooter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SpaceShooter
